name: giavang
description: A new Flutter project.
version: 7.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2
  dio: ^3.0.10
  intl: ^0.16.1
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.0
  path_provider: ^1.6.28
  sembast: ^2.4.10+4
  sentry: ^3.0.1
  flutter_bloc: ^4.0.0
  bloc: ^4.0.0
  rxdart: ^0.25.0
  equatable: ^1.2.6
  introduction_screen: ^1.0.9
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.12.0
  google_nav_bar: ^4.0.2
  url_launcher: ^5.7.10
  flutter_offline: ^1.0.0
  data_connection_checker: ^0.3.4
  pusher_client: ^2.0.0
  flutter_svg: ^0.19.3
  eva_icons_flutter: ^2.0.1
  ffi: ^1.0.0
  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_launcher_icons: ^0.8.1

  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default.jpg
    - assets/icons/call.svg
    - assets/icons/gift.svg
    - assets/icons/payment.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
